version: "3"

services:
  app:
    container_name: lexicon-demo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: lexicon-demo-nginx
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "${APP_PORT}:80"
    networks:
      - backend

networks:
  backend:
